-- ============================================================
-- Model           : fact_income_statement
-- Layer           : Gold — Fact (Periodic Snapshot)
-- Grain           : 1 row per subsidiary + period + department + classification + account
-- Account filter  : FINANCIAL_STATEMENT = 'P&L'
--                   (Income, Other Income, COGS, Expense, Other Expense)
-- FX Translation  : REPORTING_AMOUNT_USD from FACT_GL_JOURNAL (pre-translated at AVERAGERATE)
-- Source          : {{ ref('fact_gl_journal') }}
-- Key metrics     : REVENUE, COGS, GROSS_PROFIT, GROSS_MARGIN_PCT,
--                   OPERATING_EXPENSE, EBITDA, DA_AMOUNT, EBIT,
--                   INTEREST_EXPENSE, NET_INCOME + prior-period variance
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'incremental',
        schema               = 'GOLD',
        unique_key           = 'INCOME_STATEMENT_KEY',
        incremental_strategy = 'merge',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'fact']
    )
}}

WITH gl AS (

    SELECT * FROM {{ ref('fact_gl_journal') }}
    WHERE FINANCIAL_STATEMENT = 'P&L'
      AND ELIMINATE = FALSE       -- exclude intercompany elimination entries

),

period_lookup AS (
    SELECT PERIOD_KEY, PERIOD_ID, START_DATE, END_DATE, FISCAL_YEAR, FISCAL_QUARTER
    FROM {{ ref('dim_period') }}
),

account_lookup AS (
    SELECT ACCOUNT_KEY, PL_CATEGORY, IS_DA, CASH_FLOW_RATE
    FROM {{ ref('dim_account') }}
),

-- aggregate to grain: subsidiary + period + department + classification + account
aggregated AS (

    SELECT
        gl.SUBSIDIARY_KEY,
        gl.PERIOD_KEY,
        gl.DEPARTMENT_KEY,
        gl.CLASSIFICATION_KEY,
        gl.ACCOUNT_KEY,

        -- Revenue: Income account types (sign-flip: credits are positive revenue in NetSuite)
        SUM(CASE WHEN a.PL_CATEGORY = 'Revenue'
                 THEN -1 * gl.REPORTING_AMOUNT_USD ELSE 0 END)    AS REVENUE,

        -- COGS
        SUM(CASE WHEN a.PL_CATEGORY = 'COGS'
                 THEN gl.REPORTING_AMOUNT_USD ELSE 0 END)          AS COGS,

        -- Operating Expense (excl. D&A and interest — broken out below)
        SUM(CASE WHEN a.PL_CATEGORY = 'Operating Expense'
                  AND a.IS_DA = FALSE
                  AND a.CASH_FLOW_RATE != 'Financing'
                 THEN gl.REPORTING_AMOUNT_USD ELSE 0 END)          AS OPERATING_EXPENSE,

        -- D&A component of operating expense
        SUM(CASE WHEN a.PL_CATEGORY = 'Operating Expense'
                  AND a.IS_DA = TRUE
                 THEN gl.REPORTING_AMOUNT_USD ELSE 0 END)          AS DA_AMOUNT,

        -- Interest expense (financing cash flow accounts in P&L)
        SUM(CASE WHEN a.PL_CATEGORY = 'Operating Expense'
                  AND a.CASH_FLOW_RATE = 'Financing'
                 THEN gl.REPORTING_AMOUNT_USD ELSE 0 END)          AS INTEREST_EXPENSE

    FROM gl
    LEFT JOIN account_lookup a ON gl.ACCOUNT_KEY = a.ACCOUNT_KEY
    GROUP BY 1, 2, 3, 4, 5

),

-- prior period lookup for variance calculation
with_prior AS (

    SELECT
        a.*,
        p.START_DATE,
        p.END_DATE,
        p.FISCAL_YEAR,
        p.FISCAL_QUARTER,

        -- derived P&L metrics
        a.REVENUE - a.COGS                                         AS GROSS_PROFIT,
        CASE WHEN a.REVENUE <> 0
             THEN ROUND((a.REVENUE - a.COGS) / a.REVENUE * 100, 2)
             ELSE NULL END                                         AS GROSS_MARGIN_PCT,
        a.REVENUE - a.COGS - a.OPERATING_EXPENSE - a.DA_AMOUNT    AS EBITDA,
        a.REVENUE - a.COGS - a.OPERATING_EXPENSE - a.DA_AMOUNT
            - a.DA_AMOUNT                                          AS EBIT,
        a.REVENUE - a.COGS - a.OPERATING_EXPENSE
            - a.DA_AMOUNT - a.INTEREST_EXPENSE                    AS NET_INCOME,

        -- prior period net income via LAG over period ordered by start date
        LAG(
            a.REVENUE - a.COGS - a.OPERATING_EXPENSE
            - a.DA_AMOUNT - a.INTEREST_EXPENSE
        ) OVER (
            PARTITION BY a.SUBSIDIARY_KEY, a.DEPARTMENT_KEY,
                         a.CLASSIFICATION_KEY, a.ACCOUNT_KEY
            ORDER BY p.START_DATE
        )                                                          AS PRIOR_PERIOD_NET_INCOME

    FROM aggregated a
    LEFT JOIN period_lookup p ON a.PERIOD_KEY = p.PERIOD_KEY

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'SUBSIDIARY_KEY', 'PERIOD_KEY', 'DEPARTMENT_KEY',
            'CLASSIFICATION_KEY', 'ACCOUNT_KEY'
        ]) }}                                                      AS INCOME_STATEMENT_KEY,

        SUBSIDIARY_KEY,
        PERIOD_KEY,
        DEPARTMENT_KEY,
        CLASSIFICATION_KEY,
        ACCOUNT_KEY,

        REVENUE,
        COGS,
        GROSS_PROFIT,
        GROSS_MARGIN_PCT,
        OPERATING_EXPENSE,
        EBITDA,
        DA_AMOUNT,
        EBIT,
        INTEREST_EXPENSE,
        NET_INCOME,
        PRIOR_PERIOD_NET_INCOME,

        NET_INCOME - PRIOR_PERIOD_NET_INCOME                       AS VARIANCE,
        CASE WHEN PRIOR_PERIOD_NET_INCOME <> 0
             THEN ROUND(
                 (NET_INCOME - PRIOR_PERIOD_NET_INCOME)
                 / ABS(PRIOR_PERIOD_NET_INCOME) * 100, 2)
             ELSE NULL END                                         AS VARIANCE_PCT,

        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM with_prior

)

SELECT * FROM final
