-- ============================================================
-- Model           : fact_cash_flow
-- Layer           : Gold — Fact (Periodic Snapshot)
-- Grain           : 1 row per subsidiary + period + cash flow category + account
-- Account filter  : CASH_FLOW_RATE IS NOT NULL
--                   (Operating, Investing, Financing accounts only)
-- FX Translation  : REPORTING_AMOUNT_USD from FACT_GL_JOURNAL
--                   AVERAGERATE for P&L-derived movements
--                   CURRENTRATE for balance sheet movements
--                   (rate selection applied in Silver transactionaccountingline)
-- Source          : {{ ref('fact_gl_journal') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'incremental',
        schema               = 'GOLD',
        unique_key           = 'CASH_FLOW_KEY',
        incremental_strategy = 'merge',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'fact']
    )
}}

WITH gl AS (

    SELECT * FROM {{ ref('fact_gl_journal') }}
    WHERE CASH_FLOW_RATE IS NOT NULL    -- only accounts classified for Cash Flow Statement
      AND ELIMINATE = FALSE

),

period_lookup AS (
    SELECT PERIOD_KEY, PERIOD_ID, START_DATE, END_DATE
    FROM {{ ref('dim_period') }}
    WHERE IS_POSTING = TRUE
      AND IS_ADJUST  = FALSE
),

-- period movements by subsidiary + period + cash flow category + account
movements AS (

    SELECT
        gl.SUBSIDIARY_KEY,
        gl.PERIOD_KEY,
        gl.ACCOUNT_KEY,
        gl.CASH_FLOW_RATE                                          AS CASH_FLOW_CATEGORY,
        p.START_DATE,
        SUM(gl.REPORTING_AMOUNT_USD)                               AS CASH_MOVEMENT,
        SUM(gl.REPORTING_AMOUNT_USD)                               AS CASH_MOVEMENT_USD

    FROM gl
    LEFT JOIN period_lookup p ON gl.PERIOD_KEY = p.PERIOD_KEY
    GROUP BY 1, 2, 3, 4, 5

),

-- opening and closing cash: cumulative sum of Operating + Investing + Financing movements
with_balances AS (

    SELECT
        *,

        -- opening cash: cumulative total before this period
        COALESCE(
            SUM(CASH_MOVEMENT_USD) OVER (
                PARTITION BY SUBSIDIARY_KEY
                ORDER BY START_DATE
                ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
            ), 0
        )                                                          AS OPENING_CASH,

        -- closing cash: cumulative total including this period
        SUM(CASH_MOVEMENT_USD) OVER (
            PARTITION BY SUBSIDIARY_KEY
            ORDER BY START_DATE
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )                                                          AS CLOSING_CASH

    FROM movements

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'SUBSIDIARY_KEY', 'PERIOD_KEY', 'ACCOUNT_KEY', 'CASH_FLOW_CATEGORY'
        ]) }}                                                      AS CASH_FLOW_KEY,

        SUBSIDIARY_KEY,
        PERIOD_KEY,
        ACCOUNT_KEY,
        CASH_FLOW_CATEGORY,
        CASH_MOVEMENT,
        CASH_MOVEMENT_USD,
        OPENING_CASH,
        CLOSING_CASH,

        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM with_balances

)

SELECT * FROM final
