-- ============================================================
-- Model           : fact_balance_sheet
-- Layer           : Gold — Fact (Periodic Snapshot)
-- Grain           : 1 row per subsidiary + period-end + account
-- Account filter  : FINANCIAL_STATEMENT = 'Balance Sheet'
--                   (Asset, Liability, Equity account types)
-- Balance logic   : CUMULATIVE — closing balance = SUM of all movements
--                   from the earliest period through the current period-end.
--                   DO NOT use period-movement logic — this is the most
--                   common Balance Sheet modelling error.
-- FX Translation  : REPORTING_AMOUNT_USD from FACT_GL_JOURNAL
--                   CURRENTRATE for assets/liabilities · HISTORICALRATE for equity
--                   (rate selection handled in Silver transactionaccountingline)
-- Source          : {{ ref('fact_gl_journal') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'incremental',
        schema               = 'GOLD',
        unique_key           = 'BALANCE_SHEET_KEY',
        incremental_strategy = 'merge',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'fact']
    )
}}

WITH gl AS (
    SELECT * FROM "BUI_BHANU_RAMIREDDY_DB"."GOLD"."fact_gl_journal"
    WHERE FINANCIAL_STATEMENT = 'Balance Sheet'
      AND COALESCE(ELIMINATE, FALSE) = FALSE   -- ← handles NULLs as non-eliminated
),

period_lookup AS (
    SELECT PERIOD_KEY, PERIOD_ID, START_DATE, END_DATE
    FROM {{ ref('dim_period') }}
    WHERE IS_POSTING = TRUE
      AND IS_ADJUST  = FALSE
),

account_lookup AS (
    SELECT ACCOUNT_KEY, BS_CATEGORY
    FROM {{ ref('dim_account') }}
),

-- period-level movement per subsidiary + account
period_movements AS (

    SELECT
        gl.SUBSIDIARY_KEY,
        gl.PERIOD_KEY,
        gl.ACCOUNT_KEY,
        a.BS_CATEGORY,
        p.START_DATE,
        p.END_DATE,
        SUM(gl.REPORTING_AMOUNT_USD)                               AS PERIOD_MOVEMENT

    FROM gl
    LEFT JOIN period_lookup  p ON gl.PERIOD_KEY  = p.PERIOD_KEY
    LEFT JOIN account_lookup a ON gl.ACCOUNT_KEY = a.ACCOUNT_KEY
    GROUP BY 1, 2, 3, 4, 5, 6

),

-- step 1: calculate cumulative balances via self-join
cumulative_raw AS (

    SELECT
        cur.SUBSIDIARY_KEY,
        cur.PERIOD_KEY,
        cur.ACCOUNT_KEY,
        cur.BS_CATEGORY,
        cur.PERIOD_MOVEMENT,
        cur.START_DATE,
        SUM(prev.PERIOD_MOVEMENT)                                  AS CLOSING_BALANCE

    FROM period_movements cur
    JOIN period_movements prev
        ON  prev.SUBSIDIARY_KEY = cur.SUBSIDIARY_KEY
        AND prev.ACCOUNT_KEY    = cur.ACCOUNT_KEY
        AND prev.START_DATE    <= cur.START_DATE
    GROUP BY 1, 2, 3, 4, 5, 6

),

-- step 2: deduplicate then apply LAG (no nesting)
deduped AS (

    SELECT
        SUBSIDIARY_KEY,
        PERIOD_KEY,
        ACCOUNT_KEY,
        BS_CATEGORY,
        PERIOD_MOVEMENT,
        CLOSING_BALANCE - PERIOD_MOVEMENT                         AS OPENING_BALANCE,
        CLOSING_BALANCE,
        CLOSING_BALANCE                                           AS CLOSING_BALANCE_USD,
        LAG(CLOSING_BALANCE) OVER (
            PARTITION BY SUBSIDIARY_KEY, ACCOUNT_KEY
            ORDER BY START_DATE
        )                                                         AS PRIOR_PERIOD_BALANCE

    FROM cumulative_raw

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'SUBSIDIARY_KEY', 'PERIOD_KEY', 'ACCOUNT_KEY'
        ]) }}                                                      AS BALANCE_SHEET_KEY,

        SUBSIDIARY_KEY,
        PERIOD_KEY,
        ACCOUNT_KEY,
        OPENING_BALANCE,
        PERIOD_MOVEMENT,
        CLOSING_BALANCE,
        CLOSING_BALANCE_USD,
        PRIOR_PERIOD_BALANCE,

        CLOSING_BALANCE - COALESCE(PRIOR_PERIOD_BALANCE, 0)       AS BALANCE_VARIANCE,

        -- net debt: total debt liabilities minus cash and cash equivalents
        -- NOTE: populate via a separate analytical view; NULL here as it requires
        -- cross-account aggregation not available at this grain
        CAST(NULL AS NUMBER(18,4))                                 AS NET_DEBT,

        BS_CATEGORY,

        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM deduped

)

SELECT * FROM final
