-- ============================================================
-- Model           : fact_trial_balance
-- Layer           : Gold — Fact (Periodic Snapshot)
-- Grain           : 1 row per subsidiary + period + account (all account types)
-- Account filter  : All accounts (no FINANCIAL_STATEMENT filter)
--                   Includes both elimination and non-elimination entries
--                   for intercompany reconciliation
-- FX Translation  : REPORTING_AMOUNT_USD from FACT_GL_JOURNAL
-- Source          : {{ ref('fact_gl_journal') }}
-- Purpose         : Audit drill-down, due diligence, intercompany reconciliation.
--                   Drillable to TRANSACTION_ID in source.
--                   Elimination entries identifiable via IS_ELIMINATION flag.
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'incremental',
        schema               = 'GOLD',
        unique_key           = 'TRIAL_BALANCE_KEY',
        incremental_strategy = 'merge',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'fact']
    )
}}

WITH gl AS (

    -- include ALL entries including elimination (IS_ELIMINATION for reconciliation)
    SELECT * FROM {{ ref('fact_gl_journal') }}

),

period_lookup AS (
    SELECT PERIOD_KEY, PERIOD_ID, START_DATE
    FROM {{ ref('dim_period') }}
    WHERE IS_POSTING = TRUE
),

subsidiary_lookup AS (
    SELECT SUBSIDIARY_KEY, IS_ELIMINATION
    FROM {{ ref('dim_subsidiary') }}
),

-- period-level activity per subsidiary + period + account
period_activity AS (

    SELECT
        gl.SUBSIDIARY_KEY,
        gl.PERIOD_KEY,
        gl.ACCOUNT_KEY,
        gl.FINANCIAL_STATEMENT,
        sl.IS_ELIMINATION,
        p.START_DATE,
        SUM(gl.DEBIT_AMOUNT)                                       AS PERIOD_DEBIT,
        SUM(gl.CREDIT_AMOUNT)                                      AS PERIOD_CREDIT,
        SUM(gl.REPORTING_AMOUNT_USD)                               AS PERIOD_MOVEMENT

    FROM gl
    LEFT JOIN period_lookup    p  ON gl.PERIOD_KEY    = p.PERIOD_KEY
    LEFT JOIN subsidiary_lookup sl ON gl.SUBSIDIARY_KEY = sl.SUBSIDIARY_KEY
    GROUP BY 1, 2, 3, 4, 5, 6

),

-- cumulative closing balance (same logic as Balance Sheet)
with_balances AS (

    SELECT
        *,
        COALESCE(
            SUM(PERIOD_MOVEMENT) OVER (
                PARTITION BY SUBSIDIARY_KEY, ACCOUNT_KEY
                ORDER BY START_DATE
                ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
            ), 0
        )                                                          AS OPENING_BALANCE,

        SUM(PERIOD_MOVEMENT) OVER (
            PARTITION BY SUBSIDIARY_KEY, ACCOUNT_KEY
            ORDER BY START_DATE
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )                                                          AS CLOSING_BALANCE

    FROM period_activity

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key([
            'SUBSIDIARY_KEY', 'PERIOD_KEY', 'ACCOUNT_KEY'
        ]) }}                                                      AS TRIAL_BALANCE_KEY,

        SUBSIDIARY_KEY,
        PERIOD_KEY,
        ACCOUNT_KEY,
        OPENING_BALANCE,
        PERIOD_DEBIT,
        PERIOD_CREDIT,
        PERIOD_MOVEMENT,
        CLOSING_BALANCE,
        FINANCIAL_STATEMENT,
        IS_ELIMINATION,

        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM with_balances

)

SELECT * FROM final
