-- ============================================================
-- Model           : fact_gl_journal
-- Layer           : Gold — Fact
-- Grain           : 1 row per posted accounting line
--                   (TRANSACTION_ID + LINE_ID + ACCOUNTING_BOOK_ID)
-- Account filter  : All account types (POSTING=TRUE enforced in Silver)
-- FX Translation  : REPORTING_AMOUNT_USD pre-computed in Silver transactionaccountingline
--                   AVERAGERATE for P&L · CURRENTRATE for BS assets/liabilities
--                   HISTORICALRATE for equity
-- Source          : {{ source('silver', 'transactionaccountingline') }}
-- Dimensions      : DIM_ACCOUNT, DIM_SUBSIDIARY, DIM_PERIOD, DIM_DEPARTMENT,
--                   DIM_CLASSIFICATION, DIM_CURRENCY, DIM_ENTITY
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'incremental',
        schema               = 'GOLD',
        unique_key           = 'GL_JOURNAL_KEY',
        incremental_strategy = 'merge',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'fact']
    )
}}

WITH gl_source AS (

    SELECT * FROM {{ ref('transactionaccountingline') }}
    {% if is_incremental() %}
    WHERE SILVER_UPDATED_ON_TS_UTC > (SELECT MAX(DW_UPDATED_AT) FROM {{ this }})
    {% endif %}

),

-- dimension surrogate key lookups
dim_account AS (
    SELECT ACCOUNT_KEY, ACCOUNT_ID FROM {{ ref('dim_account') }}
),
dim_subsidiary AS (
    SELECT SUBSIDIARY_KEY, SUBSIDIARY_ID FROM {{ ref('dim_subsidiary') }}
),
dim_period AS (
    SELECT PERIOD_KEY, PERIOD_ID FROM {{ ref('dim_period') }}
),
dim_department AS (
    SELECT DEPARTMENT_KEY, DEPARTMENT_ID FROM {{ ref('dim_department') }}
),
dim_classification AS (
    SELECT CLASSIFICATION_KEY, CLASS_ID FROM {{ ref('dim_classification') }}
),
dim_currency AS (
    SELECT CURRENCY_KEY, CURRENCY_ID FROM {{ ref('dim_currency') }}
),
dim_entity AS (
    SELECT ENTITY_KEY, ENTITY_ID FROM {{ ref('dim_entity') }}
),

joined AS (

    SELECT
        -- fact surrogate key
        {{ dbt_utils.generate_surrogate_key([
            'gl.TRANSACTION_ID', 'gl.LINE_ID', 'gl.ACCOUNTING_BOOK_ID'
        ]) }}                                                      AS GL_JOURNAL_KEY,

        -- degenerate dimensions (transaction identifiers kept on fact)
        gl.TRANSACTION_ID,
        gl.LINE_ID,
        gl.ACCOUNTING_BOOK_ID,
        gl.TRANSACTION_REF,
        gl.TRANSACTION_DATE,
        gl.TRANSACTION_TYPE,

        -- dimension foreign keys
        da.ACCOUNT_KEY,
        ds.SUBSIDIARY_KEY,
        dp.PERIOD_KEY,
        dd.DEPARTMENT_KEY,
        dc.CLASSIFICATION_KEY,
        dcu.CURRENCY_KEY,
        de.ENTITY_KEY,

        -- measures — functional currency (as posted in subsidiary currency)
        gl.DEBIT_AMOUNT,
        gl.CREDIT_AMOUNT,
        gl.NET_AMOUNT,
        gl.FUNCTIONAL_AMOUNT,

        -- measures — USD reporting (pre-translated in Silver)
        gl.REPORTING_AMOUNT_USD,

        -- FX rates carried for audit transparency
        gl.FX_AVERAGE_RATE,
        gl.FX_CURRENT_RATE,
        gl.FX_HISTORICAL_RATE,

        -- posting and classification flags
        gl.IS_POSTING,
        gl.IS_COGS,
        gl.ELIMINATE,
        gl.FINANCIAL_STATEMENT,
        gl.PL_CATEGORY,
        gl.BS_CATEGORY,
        gl.CASH_FLOW_RATE,

        -- audit columns
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM gl_source gl

    -- LEFT JOINs: preserve all GL lines even if a dimension lookup is missing
    LEFT JOIN dim_account     da  ON gl.ACCOUNT_ID              = da.ACCOUNT_ID
    LEFT JOIN dim_subsidiary  ds  ON gl.SUBSIDIARY_ID           = ds.SUBSIDIARY_ID
    LEFT JOIN dim_period      dp  ON gl.PERIOD_ID               = dp.PERIOD_ID
    LEFT JOIN dim_department  dd  ON gl.DEPARTMENT_ID           = dd.DEPARTMENT_ID
    LEFT JOIN dim_classification dc ON gl.CLASS_ID              = dc.CLASS_ID
    LEFT JOIN dim_currency    dcu ON gl.TRANSACTION_CURRENCY_ID = dcu.CURRENCY_ID
    LEFT JOIN dim_entity      de  ON gl.ENTITY_ID               = de.ENTITY_ID

)

SELECT * FROM joined
