-- ============================================================
-- Test        : assert_gl_posting_only
-- Layer       : Gold — Singular Test
-- Purpose     : Verifies that every row in FACT_GL_JOURNAL has IS_POSTING = TRUE.
--               Non-posting entries must be excluded in Silver — this test
--               confirms the filter held through to Gold.
-- Passes when : Returns 0 rows
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================

SELECT
    GL_JOURNAL_KEY,
    TRANSACTION_ID,
    LINE_ID,
    IS_POSTING
FROM {{ ref('fact_gl_journal') }}
WHERE IS_POSTING IS DISTINCT FROM TRUE
