-- ============================================================
-- Test        : assert_balance_sheet_equation
-- Layer       : Gold — Singular Test
-- Purpose     : Verifies that Total Assets = Total Liabilities + Equity
--               for every subsidiary at every period-end.
--               A non-zero result means the Balance Sheet does not balance —
--               this must be investigated before any board pack is distributed.
-- Passes when : Returns 0 rows
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================

WITH balance_by_category AS (

    SELECT
        bs.SUBSIDIARY_KEY,
        bs.PERIOD_KEY,
        da.BS_CATEGORY,
        SUM(bs.CLOSING_BALANCE)                                    AS TOTAL_BALANCE

    FROM {{ ref('fact_balance_sheet') }} bs
    LEFT JOIN {{ ref('dim_account') }} da ON bs.ACCOUNT_KEY = da.ACCOUNT_KEY

    GROUP BY 1, 2, 3

),

pivoted AS (

    SELECT
        SUBSIDIARY_KEY,
        PERIOD_KEY,

        SUM(CASE WHEN BS_CATEGORY IN ('Current Asset', 'Non-Current Asset')
                 THEN TOTAL_BALANCE ELSE 0 END)                    AS TOTAL_ASSETS,

        SUM(CASE WHEN BS_CATEGORY IN ('Current Liability', 'Non-Current Liability')
                 THEN TOTAL_BALANCE ELSE 0 END)                    AS TOTAL_LIABILITIES,

        SUM(CASE WHEN BS_CATEGORY = 'Equity'
                 THEN TOTAL_BALANCE ELSE 0 END)                    AS TOTAL_EQUITY

    FROM balance_by_category
    GROUP BY 1, 2

),

equation_check AS (

    SELECT
        SUBSIDIARY_KEY,
        PERIOD_KEY,
        TOTAL_ASSETS,
        TOTAL_LIABILITIES,
        TOTAL_EQUITY,
        TOTAL_ASSETS - (TOTAL_LIABILITIES + TOTAL_EQUITY)          AS IMBALANCE

    FROM pivoted

)

-- Return rows only where the equation fails (imbalance > threshold of $0.01 for rounding)
SELECT *
FROM equation_check
WHERE ABS(IMBALANCE) > 0.01
