-- ============================================================
-- Snapshot    : dim_item_snapshot
-- Layer       : Gold — SCD2 History
-- Grain       : 1 row per item version (ITEM_ID + dbt_scd_id)
-- Strategy    : check — detects changes across all tracked columns
-- Source      : {{ source('silver', 'item') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{% snapshot dim_item_snapshot %}

{{
    config(
        target_schema  = var('gold_schema', 'GOLD'),
        unique_key     = 'ITEM_ID',
        strategy       = 'check',
        check_cols     = [
            'ITEM_CODE', 'DISPLAY_NAME', 'ITEM_DESCRIPTION', 'ITEM_TYPE',
            'SUBSIDIARY', 'DEPARTMENT_ID', 'CLASS_ID', 'LOCATION_ID', 'IS_INACTIVE'
        ],
        tags           = ['gold', 'scd2']
    )
}}

SELECT
    ITEM_ID,
    ITEM_CODE,
    DISPLAY_NAME,
    ITEM_DESCRIPTION,
    ITEM_TYPE,
    SUBSIDIARY,
    DEPARTMENT_ID,
    CLASS_ID,
    LOCATION_ID,
    IS_INACTIVE,
    CURRENT_TIMESTAMP()   AS DW_CREATED_AT,
    CURRENT_TIMESTAMP()   AS DW_UPDATED_AT,
    'NETSUITE'            AS DW_SOURCE_SYSTEM,
    '{{ invocation_id }}' AS DW_BATCH_ID
FROM {{ ref('item') }}

{% endsnapshot %}
