-- ============================================================
-- Snapshot    : dim_entity_snapshot
-- Layer       : Gold — SCD2 History
-- Grain       : 1 row per entity version (ENTITY_ID + dbt_scd_id)
-- Strategy    : check — detects changes across all tracked columns
-- Source      : {{ source('silver', 'entity') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{% snapshot dim_entity_snapshot %}

{{
    config(
        target_schema  = var('gold_schema', 'GOLD'),
        unique_key     = 'ENTITY_ID',
        strategy       = 'check',
        check_cols     = [
            'ENTITY_TYPE', 'ENTITY_NUMBER', 'ENTITY_CODE', 'ENTITY_FULL_NAME',
            'FIRST_NAME', 'LAST_NAME', 'CUSTOMER_ID', 'VENDOR_ID',
            'EMPLOYEE_ID', 'PARENT_ENTITY_ID', 'IS_INACTIVE'
        ],
        tags           = ['gold', 'scd2']
    )
}}

SELECT
    ENTITY_ID,
    ENTITY_TYPE,
    ENTITY_NUMBER,
    ENTITY_CODE,
    ENTITY_FULL_NAME,
    FIRST_NAME,
    LAST_NAME,
    CUSTOMER_ID,
    VENDOR_ID,
    EMPLOYEE_ID,
    PARENT_ENTITY_ID,
    IS_INACTIVE,
    CURRENT_TIMESTAMP()  AS DW_CREATED_AT,
    CURRENT_TIMESTAMP()  AS DW_UPDATED_AT,
    'NETSUITE'           AS DW_SOURCE_SYSTEM,
    '{{ invocation_id }}' AS DW_BATCH_ID
FROM {{ ref('entity') }}

{% endsnapshot %}
