-- ============================================================
-- Snapshot    : dim_employee_snapshot
-- Layer       : Gold — SCD2 History
-- Grain       : 1 row per employee version (EMPLOYEE_ID + dbt_scd_id)
-- Strategy    : check — detects changes across all tracked columns
-- Source      : {{ source('silver', 'employee') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{% snapshot dim_employee_snapshot %}

{{
    config(
        target_schema  = var('gold_schema', 'GOLD'),
        unique_key     = 'EMPLOYEE_ID',
        strategy       = 'check',
        check_cols     = [
            'EMPLOYEE_CODE', 'FIRST_NAME', 'LAST_NAME',
            'DEPARTMENT_ID', 'SUBSIDIARY_ID', 'LOCATION_ID', 'IS_INACTIVE'
        ],
        tags           = ['gold', 'scd2']
    )
}}

SELECT
    EMPLOYEE_ID,
    EMPLOYEE_CODE,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    SUBSIDIARY_ID,
    LOCATION_ID,
    IS_INACTIVE,
    CURRENT_TIMESTAMP()   AS DW_CREATED_AT,
    CURRENT_TIMESTAMP()   AS DW_UPDATED_AT,
    'NETSUITE'            AS DW_SOURCE_SYSTEM,
    '{{ invocation_id }}' AS DW_BATCH_ID
FROM {{ source('silver', 'employee') }}

{% endsnapshot %}
