-- ============================================================
-- Snapshot    : dim_location_snapshot
-- Layer       : Gold — SCD2 History
-- Grain       : 1 row per location version (LOCATION_ID + dbt_scd_id)
-- Strategy    : check — detects changes across all tracked columns
-- Source      : {{ source('silver', 'location') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{% snapshot dim_location_snapshot %}

{{
    config(
        target_schema  = var('gold_schema', 'GOLD'),
        unique_key     = 'LOCATION_ID',
        strategy       = 'check',
        check_cols     = [
            'LOCATION_NAME', 'LOCATION_FULL_NAME', 'PARENT_LOCATION_ID',
            'SUBSIDIARY_ID', 'LOCATION_TYPE', 'IS_INACTIVE'
        ],
        tags           = ['gold', 'scd2']
    )
}}

SELECT
    LOCATION_ID,
    LOCATION_NAME,
    LOCATION_FULL_NAME,
    PARENT_LOCATION_ID,
    SUBSIDIARY_ID,
    LOCATION_TYPE,
    IS_INACTIVE,
    CURRENT_TIMESTAMP()   AS DW_CREATED_AT,
    CURRENT_TIMESTAMP()   AS DW_UPDATED_AT,
    'NETSUITE'            AS DW_SOURCE_SYSTEM,
    '{{ invocation_id }}' AS DW_BATCH_ID
FROM {{ ref('location') }}

{% endsnapshot %}
