-- ============================================================
-- Model       : dim_period
-- Layer       : Gold — Dimension
-- Grain       : 1 row per NetSuite fiscal period (PERIOD_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'accountingperiod') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'PERIOD_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ source('silver', 'accountingperiod') }}

),

final AS (

    SELECT
        -- surrogate key
        {{ dbt_utils.generate_surrogate_key(['PERIOD_ID']) }}      AS PERIOD_KEY,

        -- natural key
        PERIOD_ID,

        -- period attributes
        PERIOD_NAME,
        START_DATE,
        END_DATE,

        -- fiscal calendar derivations
        YEAR(START_DATE)                                           AS FISCAL_YEAR,
        QUARTER(START_DATE)                                        AS FISCAL_QUARTER,
        MONTH(START_DATE)                                          AS FISCAL_MONTH,

        -- period type flags
        IS_YEAR,
        IS_QUARTER,
        IS_ADJUST,
        IS_CLOSED,
        IS_POSTING,
        ALL_LOCKED,

        -- audit columns
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM source

)

SELECT * FROM final
