-- ============================================================
-- Model       : dim_entity
-- Layer       : Gold — Dimension (SCD2 current-row view)
-- Grain       : 1 row per entity, current version only (IS_CURRENT = TRUE)
-- SCD Type    : SCD2 — full history in dim_entity_snapshot
-- Source      : {{ ref('dim_entity_snapshot') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'ENTITY_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension', 'scd2']
    )
}}

WITH snapshot_src AS (

    SELECT * FROM {{ ref('dim_entity_snapshot') }}
    WHERE dbt_valid_to IS NULL  -- current rows only

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key(['ENTITY_ID']) }}      AS ENTITY_KEY,
        ENTITY_ID,
        ENTITY_TYPE,
        ENTITY_NUMBER,
        ENTITY_CODE,
        ENTITY_FULL_NAME,
        FIRST_NAME,
        LAST_NAME,
        CUSTOMER_ID,
        VENDOR_ID,
        EMPLOYEE_ID,
        PARENT_ENTITY_ID,
        IS_INACTIVE,

        -- SCD2 columns derived from dbt snapshot metadata
        CAST(dbt_valid_from AS DATE)                               AS EFF_START_DATE,
        CAST(dbt_valid_to   AS DATE)                               AS EFF_END_DATE,
        CASE WHEN dbt_valid_to IS NULL THEN TRUE ELSE FALSE END    AS IS_CURRENT,

        -- record hash for change detection audit
        {{ dbt_utils.generate_surrogate_key([
            'ENTITY_TYPE', 'ENTITY_FULL_NAME', 'IS_INACTIVE'
        ]) }}                                                      AS RECORD_HASH,

        DW_CREATED_AT,
        DW_UPDATED_AT,
        DW_SOURCE_SYSTEM,
        DW_BATCH_ID

    FROM snapshot_src

)

SELECT * FROM final
