-- ============================================================
-- Model       : dim_currency
-- Layer       : Gold — Dimension
-- Grain       : 1 row per currency (CURRENCY_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'currency') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'CURRENCY_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ source('silver', 'currency') }}

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key(['CURRENCY_ID']) }}    AS CURRENCY_KEY,
        CURRENCY_ID,
        CURRENCY_NAME,
        CURRENCY_SYMBOL,
        DISPLAY_SYMBOL,
        IS_BASE_CURRENCY,
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID
    FROM source

)

SELECT * FROM final
