-- ============================================================
-- Model       : dim_account
-- Layer       : Gold — Dimension
-- Grain       : 1 row per active NetSuite account (ACCOUNT_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'account') }}
-- FX Rate     : N/A — no monetary amounts in this dimension
-- Account filter: None — all active accounts included (IS_INACTIVE=FALSE applied in Silver)
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'ACCOUNT_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ source('silver', 'account') }}

),

final AS (

    SELECT
        -- surrogate key
        {{ dbt_utils.generate_surrogate_key(['ACCOUNT_ID']) }}     AS ACCOUNT_KEY,

        -- natural key
        ACCOUNT_ID,

        -- account attributes
        ACCOUNT_NUMBER,
        ACCOUNT_TYPE,
        ACCOUNT_FULL_NAME,
        ACCOUNT_DISPLAY_NAME,
        ACCOUNT_DESCRIPTION,
        PARENT_ACCOUNT_ID,
        SUBSIDIARY,

        -- financial statement classification (derived in Silver)
        FINANCIAL_STATEMENT,
        PL_CATEGORY,
        BS_CATEGORY,
        CASH_FLOW_RATE,
        GENERAL_RATE,

        -- flags
        IS_SUMMARY,
        IS_INACTIVE,

        -- D&A flag: accounts whose PL_CATEGORY = 'Operating Expense' and
        -- account name contains depreciation / amortisation signals
        CASE
            WHEN PL_CATEGORY = 'Operating Expense'
             AND (
                  UPPER(ACCOUNT_FULL_NAME) LIKE '%DEPRECIATION%'
               OR UPPER(ACCOUNT_FULL_NAME) LIKE '%AMORTISATION%'
               OR UPPER(ACCOUNT_FULL_NAME) LIKE '%AMORTIZATION%'
             )
            THEN TRUE
            ELSE FALSE
        END                                                        AS IS_DA,

        -- audit columns
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM source

)

SELECT * FROM final
