-- ============================================================
-- Model       : dim_transaction_status
-- Layer       : Gold — Dimension
-- Grain       : 1 row per transaction status code (TRANSACTION_STATUS_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'transactionstatus') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'TRANSACTION_STATUS_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ ref('transactionstatus') }}

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key(['TRANSACTION_STATUS_ID']) }} AS TRANSACTION_STATUS_KEY,
        TRANSACTION_STATUS_ID,
        STATUS_NAME,
        STATUS_FULL_NAME,
        TRANSACTION_TYPE,
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID
    FROM source

)

SELECT * FROM final
