-- ============================================================
-- Model       : dim_item
-- Layer       : Gold — Dimension (SCD2 current-row view)
-- Grain       : 1 row per item, current version only
-- Source      : {{ ref('dim_item_snapshot') }}
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'ITEM_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension', 'scd2']
    )
}}

WITH snapshot_src AS (

    SELECT * FROM {{ ref('dim_item_snapshot') }}
    WHERE dbt_valid_to IS NULL

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key(['ITEM_ID']) }}        AS ITEM_KEY,
        ITEM_ID,
        ITEM_CODE,
        DISPLAY_NAME,
        ITEM_DESCRIPTION,
        ITEM_TYPE,
        SUBSIDIARY,
        DEPARTMENT_ID,
        CLASS_ID,
        LOCATION_ID,
        IS_INACTIVE,
        CAST(dbt_valid_from AS DATE)                               AS EFF_START_DATE,
        CAST(dbt_valid_to   AS DATE)                               AS EFF_END_DATE,
        CASE WHEN dbt_valid_to IS NULL THEN TRUE ELSE FALSE END    AS IS_CURRENT,
        {{ dbt_utils.generate_surrogate_key([
            'ITEM_CODE', 'DISPLAY_NAME', 'ITEM_TYPE', 'IS_INACTIVE'
        ]) }}                                                      AS RECORD_HASH,
        DW_CREATED_AT,
        DW_UPDATED_AT,
        DW_SOURCE_SYSTEM,
        DW_BATCH_ID
    FROM snapshot_src

)

SELECT * FROM final
