-- ============================================================
-- Model       : dim_department
-- Layer       : Gold — Dimension
-- Grain       : 1 row per department / cost centre (DEPARTMENT_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'department') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'DEPARTMENT_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ source('silver', 'department') }}

),

final AS (

    SELECT
        {{ dbt_utils.generate_surrogate_key(['DEPARTMENT_ID']) }}  AS DEPARTMENT_KEY,
        DEPARTMENT_ID,
        DEPARTMENT_NAME,
        DEPARTMENT_FULL_NAME,
        PARENT_DEPARTMENT_ID,
        SUBSIDIARY,
        IS_INACTIVE,
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID
    FROM source

)

SELECT * FROM final
