-- ============================================================
-- Model       : dim_subsidiary
-- Layer       : Gold — Dimension
-- Grain       : 1 row per legal entity / portfolio company (SUBSIDIARY_ID)
-- SCD Type    : SCD1 — overwrite on change
-- Source      : {{ source('silver', 'subsidiary') }}
-- FX Rate     : N/A
-- Generated by gold-script-generator | 2026-06-18T UTC
-- ============================================================
{{
    config(
        materialized         = 'table',
        schema               = 'GOLD',
        unique_key           = 'SUBSIDIARY_KEY',
        on_schema_change     = 'append_new_columns',
        tags                 = ['gold', 'dimension']
    )
}}

WITH source AS (

    SELECT * FROM {{ ref('subsidiary') }}

),

final AS (

    SELECT
        -- surrogate key
        {{ dbt_utils.generate_surrogate_key(['SUBSIDIARY_ID']) }}  AS SUBSIDIARY_KEY,

        -- natural key
        SUBSIDIARY_ID,

        -- subsidiary attributes
        SUBSIDIARY_NAME,
        SUBSIDIARY_FULL_NAME,
        LEGAL_NAME,
        PARENT_SUBSIDIARY_ID,
        CURRENCY_ID,
        COUNTRY,

        -- consolidation flags
        IS_ELIMINATION,

        -- IS_PARENT_ENTITY: true when this subsidiary has no parent (i.e. is PCP Holdings)
        CASE WHEN PARENT_SUBSIDIARY_ID IS NULL THEN TRUE ELSE FALSE END AS IS_PARENT_ENTITY,

        FISCAL_CALENDAR_ID,
        FEDERAL_ID_NUMBER,

        -- audit columns
        CURRENT_TIMESTAMP()                                        AS DW_CREATED_AT,
        CURRENT_TIMESTAMP()                                        AS DW_UPDATED_AT,
        'NETSUITE'                                                 AS DW_SOURCE_SYSTEM,
        '{{ invocation_id }}'                                      AS DW_BATCH_ID

    FROM source

)

SELECT * FROM final
